spring.application.name=Springboot-API-REST
server.port=8081
spring.web.allow-cors=true

# Configuración de la base de datos MySQL en AWS RDS
spring.datasource.url=jdbc:mysql://tienda-db:3306/tienda_perritos?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=alumno
spring.datasource.password=alumno123
spring.datasource.platform=mysql

# Configuraci�n de Hibernate
spring.jpa.database=mysql
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html