server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Soporte para las rutas de React (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso para el microservicio de Ventas
    location /api/v1/ventas {
        proxy_pass http://10.0.13.173:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy reverso para el microservicio de Despachos
    location /api/v1/despachos {
        proxy_pass http://10.0.13.173:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}