version: "3.9"

networks:
  tienda-net:
    driver: bridge

volumes:
  mysql_data:
    driver: local

services:

  # ==========================================
  # ENTORNO DE BASE DE DATOS (Para máquina: ec2-db)
  # ==========================================
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: tienda-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-admin123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-tienda_perritos}
      MYSQL_USER: ${MYSQL_USER:-alumno}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-alumno123}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tienda-net

  # ==========================================
  # ENTORNO DE BACKEND (Para máquina: ec2-backend)
  # ==========================================
  backend-ventas:
    build:
      context: ./backend/back-Ventas_SpringBoot
      dockerfile: Dockerfile
    container_name: tienda-backend-ventas
    restart: unless-stopped
    environment:
      DB_ENDPOINT: "10.0.0.124"        # <--- Corregido a tu IP real de ec2-db
      DB_PORT: "3306"
      SPRING_DATASOURCE_URL: "jdbc:mysql://10.0.0.124:3306/tienda_perritos?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: alumno
      SPRING_DATASOURCE_PASSWORD: alumno123
      DB_NAME: ${MYSQL_DATABASE:-tienda_perritos}
      DB_USERNAME: ${MYSQL_USER:-alumno}
      DB_PASSWORD: ${MYSQL_PASSWORD:-alumno123}
    ports:
      - "3001:8080"
    networks:
      - tienda-net

  backend-despachos:
    build:
      context: ./backend/back-Despachos_SpringBoot
      dockerfile: Dockerfile
    container_name: tienda-backend-despachos
    restart: unless-stopped
    environment:
      DB_ENDPOINT: "10.0.0.124"        # <--- Corregido a tu IP real de ec2-db
      DB_PORT: "3306"
      SPRING_DATASOURCE_URL: "jdbc:mysql://10.0.0.124:3306/tienda_perritos?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: alumno
      SPRING_DATASOURCE_PASSWORD: alumno123
      DB_NAME: ${MYSQL_DATABASE:-tienda_perritos}
      DB_USERNAME: ${MYSQL_USER:-alumno}
      DB_PASSWORD: ${MYSQL_PASSWORD:-alumno123}
    ports:
      - "3002:8080"
    networks:
      - tienda-net

  # ==========================================
  # ENTORNO DE FRONTEND (Para máquina: ec2-front)
  # ==========================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/ 
    container_name: tienda-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - tienda-net