apiVersion: v1
kind: Service
metadata:
  name: backend-despachos
  namespace: despachos
spec:
  selector:
    app: backend-despachos
  ports:
    - port: 8080
      targetPort: 8081
  type: ClusterIP
