apiVersion: v1
kind: Deployment
metadata:
  name: backend-despachos
  namespace: despachos
spec:
  selector:
    app: backend-ventas
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
