apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas
  namespace: despachos
  labels:
    app: backend-ventas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
        - name: backend-ventas
          image: 210011303411.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:ventas-latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql.despachos.svc.cluster.local:3306/tienda_perritos?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
            - name: DB_ENDPOINT
              value: "mysql.despachos.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
