name: CI/CD Tienda Perritos - DB

on:
  push:
    branches: [ "deploy" ]


jobs:
  build-push-deploy-db:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout código
        uses: actions/checkout@v3

      # 2. Configurar credenciales AWS desde GitHub Secrets
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login en Amazon ECR
      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4. Build de la imagen DB y push a ECR
      - name: Build imagen DB y Push a ECR
        run: |
          cd db
          docker build -t tienda-db .
          docker tag tienda-db:latest ${{ secrets.ECR_REPO_URL_DB }}:latest
          docker push ${{ secrets.ECR_REPO_URL_DB }}:latest

      # 5. Desplegar DB en EC2 vía SSM
      - name: Desplegar DB en EC2 vía SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Actualizar tienda-db desde ECR" \
            --parameters commands='[
              "set -e",
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
              "docker pull ${{ secrets.ECR_REPO_URL_DB }}:latest",
              "docker stop tienda-db || true",
              "docker rm tienda-db || true",
              "docker run -d --name tienda-db -p 3306:3306 --restart unless-stopped -v mysql_data:/var/lib/mysql ${{ secrets.ECR_REPO_URL_DB }}:latest"
            ]' \
            --output text